### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by ordinary-slim** [ungrichtepfl/tempdisp#1]
Explain to us!

**Comment by ungrichtepfl** [comment]
@ordinary-slim Haha nothing big, just a small Arduino setup that displays the temperature and light intensity on an LCD screen. But it's not finished yet :P

**Comment by ordinary-slim** [comment]
Then what is this variable?!
```
char* lyrics[] = {
  "Drink all the...",
  "     BOOZE!     ",
  "Hack all the... ",
  "    THINGS!     "
};
```

**Comment by ungrichtepfl** [comment]
@ordinary-slim Haha it's only a template that I used. But it's the best template!!
